[package]
name = "terminal-file-explorer"
authors = ["involvex"]
version = "0.1.0"
edition = "2021"
repository = "https://github.com/involvex/terminal-file-explorer"

[dependencies]
ratatui = "0.28"
crossterm = "0.28"
id3 = "1"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
directories = "5"
chrono = "0.4"